version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      python-development-tools:
        patterns:
          - build
          - hatchling
          - mypy
          - pytest
          - pytest-cov
          - ruff
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: build
        update-types: ["version-update:semver-major"]
      - dependency-name: hatchling
        update-types: ["version-update:semver-major"]
      - dependency-name: mypy
        update-types: ["version-update:semver-major"]
      - dependency-name: pytest
        update-types: ["version-update:semver-major"]
      - dependency-name: pytest-cov
        update-types: ["version-update:semver-major"]
      - dependency-name: ruff
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      reviewed-actions-compatible-updates:
        patterns:
          - actions/checkout
          - astral-sh/setup-uv
        update-types: ["minor", "patch"]
